[telegram]
token = ""
workers = 1
admins = []
exit_unknown_groups = false # exit groups if not added by an user id in 'admins'
log_chat = 0

[santa]
min_participants = 4
max_participants = 30 # 0 for unlimited
timeout = 72
