[telegram]
token = ""
workers = 1
admins = []
exit_unknown_groups = false # exit groups if not added by an user id in 'admins'
log_chat = 0 # chat where to post exceptions raised by callbacks (0 to disable)

[santa]
min_participants = 4
max_participants = 40 # 0 for unlimited
timeout = 7 # after how much to close secret santas, in days
start_button_on_new_group = false
